<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance (2nd ed.)

**Mastering Data-Driven Finance**

&copy; Dr. Yves J. Hilpisch | The Python Quants GmbH

<img src="http://hilpisch.com/images/py4fi_2nd_shadow.png" width="300px" align="left">

# Numerical Computing with NumPy

## Arrays with Python Lists

In [0]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]  

In [0]:
m = [v, v, v]  
m  

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [0]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [0]:
m[1][0]

0.5

In [0]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]  
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [0]:
c[1][1][0]

1

In [0]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [0]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [0]:
from copy import deepcopy
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = 3 * [deepcopy(v), ]  
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [0]:
v[0] = 'Python'  
m  

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

## Interlude: Python Array Class

In [0]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [0]:
import array

In [0]:
a = array.array('f', v)  
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [0]:
a.append(0.5)  
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [0]:
a.extend([5.0, 6.75])  
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [0]:
2 * a  

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [0]:
# causes intentional error
# a.append('string')  

In [0]:
a.tolist()  

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [0]:
f = open('array.apy', 'wb')  
a.tofile(f)  
f.close()  

In [0]:
with open('array.apy', 'wb') as f:  
    a.tofile(f)  

In [0]:
!ls -n arr*  

-rw-r--r--@ 1 503  20  32 Dec  1 11:54 array.apy


In [0]:
b = array.array('f')  

In [0]:
with open('array.apy', 'rb') as f:  
    b.fromfile(f, 5)  

In [0]:
b  

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [0]:
b = array.array('d')  

In [0]:
with open('array.apy', 'rb') as f:
    b.fromfile(f, 2)  

In [0]:
b  

array('d', [0.0004882813645963324, 0.12500002956949174])

## Regular NumPy Arrays

### The Basics

In [0]:
import numpy as np  

In [0]:
a = np.array([0, 0.5, 1.0, 1.5, 2.0])  
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [0]:
type(a)  

numpy.ndarray

In [0]:
a = np.array(['a', 'b', 'c'])  
a

array(['a', 'b', 'c'], dtype='<U1')

In [0]:
a = np.arange(2, 20, 2)  
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
a = np.arange(8, dtype=np.float)  
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [0]:
a[5:]  

array([5., 6., 7.])

In [0]:
a[:2]  

array([0., 1.])

In [0]:
a.sum()  

28.0

In [0]:
a.std()  

2.29128784747792

In [0]:
a.cumsum()  

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [0]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l  

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [0]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [0]:
2 * a  

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [0]:
a ** 2  

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [0]:
2 ** a  

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [0]:
a ** a  

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [0]:
np.exp(a)  

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [0]:
np.sqrt(a)  

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [0]:
np.sqrt(2.5)  

1.5811388300841898

In [0]:
import math  

In [0]:
math.sqrt(2.5)  

1.5811388300841898

In [0]:
# causes intentional error
# math.sqrt(a)  

In [0]:
%timeit np.sqrt(2.5)  

767 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [0]:
%timeit math.sqrt(2.5)  

78.6 ns ± 0.723 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


### Multiple Dimensions

In [0]:
b = np.array([a, a * 2])  
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [0]:
b[0]  

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [0]:
b[0, 2]  

2.0

In [0]:
b[:, 1]  

array([1., 2.])

In [0]:
b.sum()  

84.0

In [0]:
b.sum(axis=0)  

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [0]:
b.sum(axis=1)  

array([28., 56.])

In [0]:
c = np.zeros((2, 3), dtype='i', order='C')  
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [0]:
c = np.ones((2, 3, 4), dtype='i', order='C')  
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [0]:
d = np.zeros_like(c, dtype='f16', order='C')  
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [0]:
d = np.ones_like(c, dtype='f16', order='C')  
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [0]:
e = np.empty((2, 3, 2))  
e

array([[[-1.28822975e-231, -1.28822975e-231],
        [ 4.94065646e-323,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000]]])

In [0]:
f = np.empty_like(c)  
f

array([[[          0, -1879048192,           0, -1879048192],
        [         10,           0,           0,           0],
        [          0,           0,           0,           0]],

       [[          0,           0,           0,           0],
        [          0,           0,           0,           0],
        [          0,           0,           0,           0]]],
      dtype=int32)

In [0]:
np.eye(5)  

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
g = np.linspace(5, 15, 12) 
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

### Meta-Information

In [0]:
g.size  

12

In [0]:
g.itemsize  

8

In [0]:
g.ndim  

1

In [0]:
g.shape  

(12,)

In [0]:
g.dtype  

dtype('float64')

In [0]:
g.nbytes  

96

### Reshaping, Resizing, Stacking, Flattening

In [0]:
g = np.arange(15)

In [0]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
g.shape  

(15,)

In [0]:
np.shape(g) 

(15,)

In [0]:
g.reshape((3, 5))  

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
h = g.reshape((5, 3))  
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [0]:
h.T  

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [0]:
h.transpose()  

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [0]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
np.resize(g, (3, 1))  

array([[0],
       [1],
       [2]])

In [0]:
np.resize(g, (1, 5))  

array([[0, 1, 2, 3, 4]])

In [0]:
np.resize(g, (2, 5))  

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [0]:
n = np.resize(g, (5, 4))  
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 1,  2,  3,  4]])

In [0]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [0]:
np.hstack((h, 2 * h))  

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [0]:
np.vstack((h, 0.5 * h))  

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

In [0]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [0]:
h.flatten()  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
h.flatten(order='C')  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
h.flatten(order='F')  

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [0]:
for i in h.flat:  
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [0]:
for i in h.ravel(order='C'):  
    print(i, end=',')

0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,

In [0]:
for i in h.ravel(order='F'):  
    print(i, end=',')

0,3,6,9,12,1,4,7,10,13,2,5,8,11,14,

### Boolean Arrays

In [0]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [0]:
h > 8  

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [0]:
h <= 7  

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [0]:
h == 5  

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
(h == 5).astype(int)  

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
(h > 4) & (h <= 12)  

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [0]:
h[h > 8]  

array([ 9, 10, 11, 12, 13, 14])

In [0]:
h[(h > 4) & (h <= 12)]  

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
h[(h < 4) | (h >= 12)]  

array([ 0,  1,  2,  3, 12, 13, 14])

In [0]:
np.where(h > 7, 1, 0)  

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
np.where(h % 2 == 0, 'even', 'odd')  

array([['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even'],
       ['odd', 'even', 'odd'],
       ['even', 'odd', 'even']], dtype='<U4')

In [0]:
np.where(h <= 7, h * 2, h / 2)  

array([[ 0. ,  2. ,  4. ],
       [ 6. ,  8. , 10. ],
       [12. , 14. ,  4. ],
       [ 4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ]])

### Speed Comparison

In [0]:
import random
I = 5000

In [0]:
%time mat = [[random.gauss(0, 1) for j in range(I)] \
             for i in range(I)]  

CPU times: user 16.9 s, sys: 390 ms, total: 17.3 s
Wall time: 17.4 s


In [0]:
mat[0][:5]  

[-0.4602342297592762,
 -0.07820299399332144,
 1.2666740605880484,
 0.3304071298394351,
 0.2551237312223029]

In [0]:
%time sum([sum(l) for l in mat])  

CPU times: user 124 ms, sys: 1.79 ms, total: 126 ms
Wall time: 125 ms


-3250.984989010543

In [0]:
import sys
sum([sys.getsizeof(l) for l in mat])  

215200000

In [0]:
%time mat = np.random.standard_normal((I, I))  

CPU times: user 1.01 s, sys: 149 ms, total: 1.15 s
Wall time: 1.15 s


In [0]:
%time mat.sum()  

CPU times: user 26.6 ms, sys: 910 µs, total: 27.5 ms
Wall time: 26.2 ms


-7978.9521640884095

In [0]:
mat.nbytes  

200000000

In [0]:
sys.getsizeof(mat)  

200000112

### Structured Arrays

In [0]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
               ('Height', 'f'), ('Children/Pets', 'i4', 2)])  

In [0]:
dt  

dtype([('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [0]:
dt = np.dtype({'names': ['Name', 'Age', 'Height', 'Children/Pets'],
             'formats':'O int float int,int'.split()})  

In [0]:
dt  

dtype([('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [0]:
s = np.array([('Smith', 45, 1.83, (0, 1)),
              ('Jones', 53, 1.72, (2, 2))], dtype=dt)  

In [0]:
s  

array([('Smith', 45, 1.83, (0, 1)), ('Jones', 53, 1.72, (2, 2))],
      dtype=[('Name', 'O'), ('Age', '<i8'), ('Height', '<f8'), ('Children/Pets', [('f0', '<i8'), ('f1', '<i8')])])

In [0]:
type(s)  

numpy.ndarray

In [0]:
s['Name']  

array(['Smith', 'Jones'], dtype=object)

In [0]:
s['Height'].mean()  

1.775

In [0]:
s[0]  

('Smith', 45, 1.83, (0, 1))

In [0]:
s[1]['Age']  

53

## Vectorization of Code

In [0]:
np.random.seed(100)
r = np.arange(12).reshape((4, 3))  
s = np.arange(12).reshape((4, 3)) * 0.5  

In [0]:
r  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
s  

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [0]:
r + s  

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [0]:
r + 3  

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [0]:
2 * r  

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [0]:
2 * r + 3  

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [0]:
r

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
r.shape

(4, 3)

In [0]:
s = np.arange(0, 12, 4)  
s  

array([0, 4, 8])

In [0]:
r + s  

array([[ 0,  5, 10],
       [ 3,  8, 13],
       [ 6, 11, 16],
       [ 9, 14, 19]])

In [0]:
s = np.arange(0, 12, 3)  
s  

array([0, 3, 6, 9])

In [0]:
# causes intentional error
# r + s  

In [0]:
r.transpose() + s  

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20]])

In [0]:
sr = s.reshape(-1, 1)  
sr

array([[0],
       [3],
       [6],
       [9]])

In [0]:
sr.shape  

(4, 1)

In [0]:
r + s.reshape(-1, 1)  

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [0]:
def f(x):
    return 3 * x + 5  

In [0]:
f(0.5)  

6.5

In [0]:
f(r)  

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

## Memory Layout

Cf. http://eli.thegreenplace.net/2015/memory-layout-of-multi-dimensional-arrays/

In [0]:
x = np.random.standard_normal((1000000, 5))  

In [0]:
y = 2 * x + 3  

In [0]:
C = np.array((x, y), order='C')  

In [0]:
F = np.array((x, y), order='F')  

In [0]:
x = 0.0; y = 0.0  

In [0]:
C[:2].round(2)  

array([[[-1.75,  0.34,  1.15, -0.25,  0.98],
        [ 0.51,  0.22, -1.07, -0.19,  0.26],
        [-0.46,  0.44, -0.58,  0.82,  0.67],
        ...,
        [-0.05,  0.14,  0.17,  0.33,  1.39],
        [ 1.02,  0.3 , -1.23, -0.68, -0.87],
        [ 0.83, -0.73,  1.03,  0.34, -0.46]],

       [[-0.5 ,  3.69,  5.31,  2.5 ,  4.96],
        [ 4.03,  3.44,  0.86,  2.62,  3.51],
        [ 2.08,  3.87,  1.83,  4.63,  4.35],
        ...,
        [ 2.9 ,  3.28,  3.33,  3.67,  5.78],
        [ 5.04,  3.6 ,  0.54,  1.65,  1.26],
        [ 4.67,  1.54,  5.06,  3.69,  2.07]]])

In [0]:
%timeit C.sum()  

4.43 ms ± 206 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [0]:
%timeit F.sum()  

4.21 ms ± 88.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [0]:
%timeit C.sum(axis=0)  

16.5 ms ± 457 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [0]:
%timeit C.sum(axis=1)  

34.8 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [0]:
%timeit F.sum(axis=0)  

82.2 ms ± 1.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [0]:
%timeit F.sum(axis=1)  

66.1 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [0]:
F = 0.0; C = 0.0  

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>